[package]
name = "me3-mod-host-assets"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lints]
workspace = true
